Skyscanner/backpack-foundations

UNRELEASED.md, packages/bpk-foundations-web/src/base/notifications.json, packages/bpk-foundations-web/tokens/base.raw.json
=> [KOA-3645] Deprecate banner alert padding tokens

UNRELEASED.md, packages/bpk-foundations-android/package-lock.json, packages/bpk-foundations-ios/src/base/typography.json, packages/bpk-foundations-ios/tokens/base.ios.json, packages/bpk-foundations-ios/tokens/base.raw.ios.json, packages/bpk-foundations-web/package-lock.json
=> [iOS] Update textSecondaryColor for dark mode

UNRELEASED.md, packages/bpk-foundations-android/formatters/bpk.android.xml.js, packages/bpk-foundations-android/tokens/base.android.xml
This is needed to refer to other tokens in text styles.
=> KOA-4805 Include original tag in xml token version for Android

UNRELEASED.md, packages/bpk-foundations-android/package-lock.json, packages/bpk-foundations-common/package-lock.json, packages/bpk-foundations-ios/package-lock.json, packages/bpk-foundations-react-native/package-lock.json, packages/bpk-foundations-web/package-lock.json, packages/bpk-foundations-web/src/base/aliases.json, packages/bpk-foundations-web/src/base/spacing.json, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss, packages/bpk-foundations-web/tokens/breakpoints.raw.json
Adds new `xxxl` and `xxxxl` spacing sizes
=> Add two larger spacing sizes

.sassdocrc, package.json
Reverts Skyscanner/backpack-foundations#73
=> Revert "[KOA-4903]: Enable google analytics in sassdoc"

UNRELEASED.md, packages/bpk-foundations-android/tokens/base.raw.android.json, packages/bpk-foundations-common/app/typography.json, packages/bpk-foundations-ios/tokens/base.ios.json, packages/bpk-foundations-ios/tokens/base.raw.ios.json, packages/bpk-stylesheets/package-lock.json
Adding 
**font-weight:** bold;
**font-size:** 12px;
**line-height:** 16px;
=> adding the new label 3 style

UNRELEASED.md, packages/bpk-mixins/src/mixins/_buttons.scss
=> [KOA-5107] Fix link buttons font weight

UNRELEASED.md, packages/bpk-mixins/src/mixins/_badges.scss
Update badge styles to use `bpk-caption`
| Before | After |
| -- | -- |
| ![Screenshot 2022-08-02 at 15 19 01](https://user-images.githubusercontent.com/8831547/182397315-7ce2ea89-61fe-4353-b26d-1c46248b81ad.png) | ![Screenshot 2022-08-02 at 15 19 30](https://user-images.githubusercontent.com/8831547/182397410-ad48a5e0-89f7-4262-bd36-66b78bea22af.png) |
=> [KOA-5463]: Update Badge typography styles

UNRELEASED.md, packages/bpk-foundations-web/src/base/cards.json, packages/bpk-foundations-web/src/base/panels.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-mixins/src/mixins/_typography.scss
=> [KOA-5473] Upgrade to semantic tokens

UNRELEASED.md, packages/bpk-mixins/src/mixins/_forms.scss
Updates the following mixins to new semantic tokens:
- BpkRadio
- BpkCheckbox
=> [KOA-5549]: Interaction form elements semantic tokens update

UNRELEASED.md, packages/bpk-mixins/src/mixins/_typography.scss
=> [KOA-5591] Update table mixins to semantic tokens

UNRELEASED.md, packages/bpk-mixins/src/mixins/_buttons.scss
=> [KOA-5480] Fix colours in button mixins

UNRELEASED.md, packages/bpk-mixins/src/mixins/_typography.scss
=> [KOA-5589]: BpkCode colour updates

UNRELEASED.md, packages/bpk-foundations-web/src/base/aliases.json, packages/bpk-foundations-web/src/base/buttons.json, packages/bpk-foundations-web/src/base/typography.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/breakpoints.raw.json, packages/bpk-mixins/src/mixins/_buttons.scss
| Before | After |
| -- | -- |
| ![Screenshot 2022-10-18 at 15 50 54](https://user-images.githubusercontent.com/8831547/196464891-393cbfe6-cef3-42e4-af90-b5639b6d5280.png) | ![Screenshot 2022-10-18 at 15 49 46](https://user-images.githubusercontent.com/8831547/196464609-f6563beb-fc7f-425d-a8e1-e09451ccb268.png) | 
=> [KOA-5465]: Button to Label-1

UNRELEASED.md, packages/bpk-foundations-web/src/base/forms.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-mixins/src/mixins/_forms.scss
Cleaning up unused/unrequired forms tokens.
- Marks tokens as deprecated
- Updates usages to semantic tokens.
=> [KOA-5697]: Cleanup forms tokens

packages/bpk-foundations-web/src/base/typography.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-mixins/src/mixins/_typography.scss
=> [KOA-5698] Clean up typography tokens

CHANGELOG.md, UNRELEASED.md, packages/bpk-foundations-web/src/base/typography.json, packages/bpk-mixins/src/mixins/_forms.scss
=> [NO JIRA] Fix label mixin using incorrect token

UNRELEASED.md, packages/bpk-foundations-web/src/base/animations.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss
=> [KOA-5766]: Update animation tokens

UNRELEASED.md, packages/bpk-foundations-web/src/base/autosuggest.json, packages/bpk-foundations-web/src/base/badges.json, packages/bpk-foundations-web/src/base/horizontal-nav.json, packages/bpk-foundations-web/src/base/notifications.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-mixins/src/mixins/_badges.scss
=> [KOA-5765] Deprecate unused tokens

UNRELEASED.md, packages/bpk-foundations-web/src/base/buttons.json, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-mixins/src/mixins/_buttons.scss
=> [KOA-5764] Deprecate button tokens

stories/tokens/borders/borders.js, stories/tokens/borders/borders.scss, stories/tokens/borders/borders.stories.js
=> [KOA-5758] Add border tokens stories

packages/bpk-stylesheets/package-lock.json, stories/tokens/animations/animations.js, stories/tokens/animations/animations.scss, stories/tokens/animations/animations.stories.js
=> [KOA-5757] Add animation token story

stories/tokens/radii/radii.js, stories/tokens/radii/radii.scss, stories/tokens/radii/radii.stories.js
=> [KOA-5759] Add radius tokens stories

.storybook/main.js, stories/svgs/icons/icons.js, stories/svgs/icons/icons.scss, stories/svgs/icons/icons.stories.js, stories/svgs/spinners/spinners.js, stories/svgs/spinners/spinners.scss, stories/svgs/spinners/spinners.stories.js, stories/svgs/utils.js
Adding stories for svg elements
| Story | Screenshot |
| -- | -- |
| Small Icons | ![SmallIconStory](https://user-images.githubusercontent.com/8831547/217274616-b111196e-7744-43ce-9c3c-719bede4cd87.png) |
| Large Icons | ![LargeIconStory](https://user-images.githubusercontent.com/8831547/217274717-ccaa3aa9-7f7c-4040-a6e3-f46b25123cb7.png) |
| Spinners | ![SpinnerStory](https://user-images.githubusercontent.com/8831547/217274776-4114233a-0e46-4c43-aaf5-38d547643e15.png) |
=> [KOA-5773]: Add icon stories

CHANGELOG_FORMAT.md, packages/bpk-mixins/src/mixins/_svgs.scss
=> [KOA-5639] Remove backpack.github.io references

stories/tokens/animations/animations.js, stories/tokens/borders/borders.js, stories/tokens/colors/colors.js, stories/tokens/radii/radii.js, stories/tokens/spacings/spacings.js, stories/tokens/spacings/spacings.scss, stories/tokens/spacings/spacings.stories.js, stories/tokens/utils.js
=> [KOA-5761] Create spacing tokens stories

stories/svgs/icons/icons.stories.js, stories/svgs/spinners/spinners.stories.js, stories/tokens/animations/animations.stories.js, stories/tokens/colors/colors.stories.js, stories/tokens/radii/radii.stories.js, stories/tokens/shadows/shadows.js, stories/tokens/shadows/shadows.scss, stories/tokens/shadows/shadows.stories.js
=> [KOA-5760] Add shadow tokens stories

UNRELEASED.md, packages/bpk-mixins/src/mixins/_chips.scss
=> [KOA-5894]: Fixed chip cursor interaction

stories/mixins/typography/typography-styles.js, stories/mixins/typography/typography.js, stories/mixins/typography/typography.scss, stories/mixins/typography/typography.stories.js, stories/svgs/icons/icons.stories.js, stories/svgs/spinners/spinners.stories.js, stories/tokens/animations/animations.stories.js, stories/tokens/borders/borders.stories.js, stories/tokens/colors/colors.stories.js, stories/tokens/shadows/shadows.stories.js, stories/tokens/spacings/spacings.stories.js
=> [KOA-5763] Add typography mixins stories

packages/bpk-foundations-web/formatters/utils-test.js, packages/bpk-foundations-web/formatters/utils.js
=> [KOA-5762] Add check for tokens to  have the same unit

UNRELEASED.md, packages/bpk-foundations-web/src/base/buttons.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss, packages/bpk-mixins/src/mixins/_forms.scss, packages/bpk-mixins/src/mixins/_svgs.scss
=> [NO JIRA] Fix broken mixins

UNRELEASED.md, packages/bpk-foundations-web/src/base.json, packages/bpk-foundations-web/src/base/sliders.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss
=> [KOA-5922] Add private token for slider

UNRELEASED.md, packages/bpk-mixins/src/mixins/_badges.scss
=> [KOA-5948]: Remove deprecated Badge tokens and mixins

.nvmrc, CONTRIBUTING.md, UNRELEASED.md, package-lock.json, package.json, packages/bpk-foundations-android/package-lock.json, packages/bpk-foundations-common/package-lock.json, packages/bpk-foundations-ios/package-lock.json, packages/bpk-foundations-react-native/package-lock.json, packages/bpk-foundations-web/package-lock.json, packages/bpk-stylesheets/package-lock.json, packages/bpk-stylesheets/package.json
=> [KOA-6075] Migrate to Node 18

UNRELEASED.md, packages/bpk-mixins/package.json
This PR increases the required supported `node-sass` range for `bpk-mixins` to ensure it is compatible with Node 18
=> Increase node-sass range to include all new majors

UNRELEASED.md, packages/bpk-foundations-web/src/base/buttons.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss
Related Backpack Contribution PR: https://github.com/Skyscanner/backpack/pull/2997
According to the figma design: https://www.figma.com/file/irZ3YBx8vOm16ICkAr7mB3/Backpack?type=design&node-id=22719-25573&mode=design&t=ST4KjGYhpWJbrHE1-0
We need a new token for bpk card button contained background.
=> [BD-7264] add card button contained background

UNRELEASED.md, packages/bpk-foundations-web/formatters/bpk.d.ts.js, packages/bpk-foundations-web/gulpfile.babel.js, packages/bpk-foundations-web/tokens/base.es6.d.ts
Adds an additional web format that produces a `.d.ts` file for the `.es6` formatter. The change is a copy paste of the current `es6` formatter with some minor tweaks to the content. 
=> [NOJIRA]: add es6.d.ts to create .d.ts file for typescript codebases

.github/dependabot.yaml
Update major/minor dependencies only.
Related to https://github.com/Skyscanner/eslint-config-skyscanner/pull/690
=> Update dependabot.yaml to only raise PRs for Major/Minor

packages/bpk-foundations-web/src/base/aliases.json, packages/bpk-foundations-web/src/base/typography.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.d.ts, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss
- Adds letter spacing tokens for updated hero typography & upcoming display types.
See new [typography specification](https://skyscanner.atlassian.net/wiki/spaces/PD/pages/670800556/Typography+tokens).
=> [WALL-1807] Add new hero & display letter spacings

.github/workflows/release.yml
This PR fixes up some of the previous work for automating foundations CI. In this PR it handles: 
- The correct versions so that it matches the expected spec for lerna when it comes to publish, previously just passing the version number Lerna would error.
- We also handle the part that when versioning with lerna it creates changes to the package files which then when publishing causes Lerna to error due to uncommited changes
=> [LOOM-1930]: Improving automated CI to fix automated release process

CONTRIBUTING.md
Since backpack is handovered to Clover, therefore, we need to update the support team to navigate people to the right place
=> [NO-JIRA]Update support team

packages/bpk-foundations-web/src/base/icons.json, packages/bpk-foundations-web/tokens/base.common.js, packages/bpk-foundations-web/tokens/base.default.scss, packages/bpk-foundations-web/tokens/base.es6.d.ts, packages/bpk-foundations-web/tokens/base.es6.js, packages/bpk-foundations-web/tokens/base.raw.json, packages/bpk-foundations-web/tokens/base.scss
After confirmation in [backpack-design-chat](https://skyscanner.slack.com/archives/CUQ587E5D/p1744704681297709), I decided to add a new variable for the usage in [BpkStar issue](https://skyscanner.slack.com/archives/C0JHPDSSU/p1742399607817239)
=> Add-bpk-icon-size-lg

.github/workflows/release.yml
=> Add correct environment to give secrets access
